import { useAppSelector } from 'core/config/store.config';

const ALL = [
    'creer.expediteur', //
    'modifier.expediteur',
    'enregistrer.expediteur',
    'lister.expediteur',
    'retourListe.expediteur',
    'consulter.expediteur',
    'ajouter.expediteur',
    'chercher.expediteur',
    'filtrer.expediteur',
    'supprimer.expediteur',
    'creer.typeOptionSansReponse', //
    'modifier.typeOptionSansReponse',
    'enregistrer.typeOptionSansReponse',
    'lister.typeOptionSansReponse',
    'retourListe.typeOptionSansReponse',
    'consulter.typeOptionSansReponse',
    'ajouter.typeOptionSansReponse',
    'chercher.typeOptionSansReponse',
    'filtrer.typeOptionSansReponse',
    'supprimer.typeOptionSansReponse',
    'creer.identificationContrat', //
    'modifier.identificationContrat',
    'enregistrer.identificationContrat',
    'lister.identificationContrat',
    'retourListe.identificationContrat',
    'consulter.identificationContrat',
    'ajouter.identificationContrat',
    'chercher.identificationContrat',
    'filtrer.identificationContrat',
    'supprimer.identificationContrat',
    'creer.email', //
    'modifier.email',
    'enregistrer.email',
    'lister.email',
    'retourListe.email',
    'consulter.email',
    'ajouter.email',
    'chercher.email',
    'filtrer.email',
    'supprimer.email',
    'creer.questionnaire', //
    'modifier.questionnaire',
    'enregistrer.questionnaire',
    'lister.questionnaire',
    'retourListe.questionnaire',
    'consulter.questionnaire',
    'ajouter.questionnaire',
    'chercher.questionnaire',
    'filtrer.questionnaire',
    'supprimer.questionnaire',
    'creer.entiteAdverse', //
    'modifier.entiteAdverse',
    'enregistrer.entiteAdverse',
    'lister.entiteAdverse',
    'retourListe.entiteAdverse',
    'consulter.entiteAdverse',
    'ajouter.entiteAdverse',
    'chercher.entiteAdverse',
    'filtrer.entiteAdverse',
    'supprimer.entiteAdverse',
    'creer.etatQuestionnaire', //
    'modifier.etatQuestionnaire',
    'enregistrer.etatQuestionnaire',
    'lister.etatQuestionnaire',
    'retourListe.etatQuestionnaire',
    'consulter.etatQuestionnaire',
    'ajouter.etatQuestionnaire',
    'chercher.etatQuestionnaire',
    'filtrer.etatQuestionnaire',
    'supprimer.etatQuestionnaire',
    'creer.nombreTacheParCategorie', //
    'modifier.nombreTacheParCategorie',
    'enregistrer.nombreTacheParCategorie',
    'lister.nombreTacheParCategorie',
    'retourListe.nombreTacheParCategorie',
    'consulter.nombreTacheParCategorie',
    'ajouter.nombreTacheParCategorie',
    'chercher.nombreTacheParCategorie',
    'filtrer.nombreTacheParCategorie',
    'supprimer.nombreTacheParCategorie',
    'creer.identification', //
    'modifier.identification',
    'enregistrer.identification',
    'lister.identification',
    'retourListe.identification',
    'consulter.identification',
    'ajouter.identification',
    'chercher.identification',
    'filtrer.identification',
    'supprimer.identification',
    'creer.identificationDocument', //
    'modifier.identificationDocument',
    'enregistrer.identificationDocument',
    'lister.identificationDocument',
    'retourListe.identificationDocument',
    'consulter.identificationDocument',
    'ajouter.identificationDocument',
    'chercher.identificationDocument',
    'filtrer.identificationDocument',
    'supprimer.identificationDocument',
    'creer.notification', //
    'modifier.notification',
    'enregistrer.notification',
    'lister.notification',
    'retourListe.notification',
    'consulter.notification',
    'ajouter.notification',
    'chercher.notification',
    'filtrer.notification',
    'supprimer.notification',
    'creer.circonstance', //
    'modifier.circonstance',
    'enregistrer.circonstance',
    'lister.circonstance',
    'retourListe.circonstance',
    'consulter.circonstance',
    'ajouter.circonstance',
    'chercher.circonstance',
    'filtrer.circonstance',
    'supprimer.circonstance',
    'creer.victime', //
    'modifier.victime',
    'enregistrer.victime',
    'lister.victime',
    'retourListe.victime',
    'consulter.victime',
    'ajouter.victime',
    'chercher.victime',
    'filtrer.victime',
    'supprimer.victime',
    'creer.identificationTiers', //
    'modifier.identificationTiers',
    'enregistrer.identificationTiers',
    'lister.identificationTiers',
    'retourListe.identificationTiers',
    'consulter.identificationTiers',
    'ajouter.identificationTiers',
    'chercher.identificationTiers',
    'filtrer.identificationTiers',
    'supprimer.identificationTiers',
    'creer.sousDossier', //
    'modifier.sousDossier',
    'enregistrer.sousDossier',
    'lister.sousDossier',
    'retourListe.sousDossier',
    'consulter.sousDossier',
    'ajouter.sousDossier',
    'chercher.sousDossier',
    'filtrer.sousDossier',
    'supprimer.sousDossier',
    'creer.documentGed', //
    'modifier.documentGed',
    'enregistrer.documentGed',
    'lister.documentGed',
    'retourListe.documentGed',
    'consulter.documentGed',
    'ajouter.documentGed',
    'chercher.documentGed',
    'filtrer.documentGed',
    'supprimer.documentGed',
    'creer.reponse', //
    'modifier.reponse',
    'enregistrer.reponse',
    'lister.reponse',
    'retourListe.reponse',
    'consulter.reponse',
    'ajouter.reponse',
    'chercher.reponse',
    'filtrer.reponse',
    'supprimer.reponse',
    'creer.identificationAssure', //
    'modifier.identificationAssure',
    'enregistrer.identificationAssure',
    'lister.identificationAssure',
    'retourListe.identificationAssure',
    'consulter.identificationAssure',
    'ajouter.identificationAssure',
    'chercher.identificationAssure',
    'filtrer.identificationAssure',
    'supprimer.identificationAssure',
    'creer.question', //
    'modifier.question',
    'enregistrer.question',
    'lister.question',
    'retourListe.question',
    'consulter.question',
    'ajouter.question',
    'chercher.question',
    'filtrer.question',
    'supprimer.question',
    'creer.utilisateur', //
    'modifier.utilisateur',
    'enregistrer.utilisateur',
    'lister.utilisateur',
    'retourListe.utilisateur',
    'consulter.utilisateur',
    'ajouter.utilisateur',
    'chercher.utilisateur',
    'filtrer.utilisateur',
    'supprimer.utilisateur',
    'creer.ayantDroit', //
    'modifier.ayantDroit',
    'enregistrer.ayantDroit',
    'lister.ayantDroit',
    'retourListe.ayantDroit',
    'consulter.ayantDroit',
    'ajouter.ayantDroit',
    'chercher.ayantDroit',
    'filtrer.ayantDroit',
    'supprimer.ayantDroit',
    'creer.tiers', //
    'modifier.tiers',
    'enregistrer.tiers',
    'lister.tiers',
    'retourListe.tiers',
    'consulter.tiers',
    'ajouter.tiers',
    'chercher.tiers',
    'filtrer.tiers',
    'supprimer.tiers',
    'creer.etat', //
    'modifier.etat',
    'enregistrer.etat',
    'lister.etat',
    'retourListe.etat',
    'consulter.etat',
    'ajouter.etat',
    'chercher.etat',
    'filtrer.etat',
    'supprimer.etat',
    'creer.reference', //
    'modifier.reference',
    'enregistrer.reference',
    'lister.reference',
    'retourListe.reference',
    'consulter.reference',
    'ajouter.reference',
    'chercher.reference',
    'filtrer.reference',
    'supprimer.reference',
    'creer.rubrique', //
    'modifier.rubrique',
    'enregistrer.rubrique',
    'lister.rubrique',
    'retourListe.rubrique',
    'consulter.rubrique',
    'ajouter.rubrique',
    'chercher.rubrique',
    'filtrer.rubrique',
    'supprimer.rubrique',
    'creer.sinistre', //
    'modifier.sinistre',
    'enregistrer.sinistre',
    'lister.sinistre',
    'retourListe.sinistre',
    'consulter.sinistre',
    'ajouter.sinistre',
    'chercher.sinistre',
    'filtrer.sinistre',
    'supprimer.sinistre',
    'creer.typeReponse', //
    'modifier.typeReponse',
    'enregistrer.typeReponse',
    'lister.typeReponse',
    'retourListe.typeReponse',
    'consulter.typeReponse',
    'ajouter.typeReponse',
    'chercher.typeReponse',
    'filtrer.typeReponse',
    'supprimer.typeReponse',
    'creer.regleSuivi', //
    'modifier.regleSuivi',
    'enregistrer.regleSuivi',
    'lister.regleSuivi',
    'retourListe.regleSuivi',
    'consulter.regleSuivi',
    'ajouter.regleSuivi',
    'chercher.regleSuivi',
    'filtrer.regleSuivi',
    'supprimer.regleSuivi',
    'creer.historiqueEtat', //
    'modifier.historiqueEtat',
    'enregistrer.historiqueEtat',
    'lister.historiqueEtat',
    'retourListe.historiqueEtat',
    'consulter.historiqueEtat',
    'ajouter.historiqueEtat',
    'chercher.historiqueEtat',
    'filtrer.historiqueEtat',
    'supprimer.historiqueEtat',
    'creer.identificationTribunal', //
    'modifier.identificationTribunal',
    'enregistrer.identificationTribunal',
    'lister.identificationTribunal',
    'retourListe.identificationTribunal',
    'consulter.identificationTribunal',
    'ajouter.identificationTribunal',
    'chercher.identificationTribunal',
    'filtrer.identificationTribunal',
    'supprimer.identificationTribunal',
    'creer.optionReponse', //
    'modifier.optionReponse',
    'enregistrer.optionReponse',
    'lister.optionReponse',
    'retourListe.optionReponse',
    'consulter.optionReponse',
    'ajouter.optionReponse',
    'chercher.optionReponse',
    'filtrer.optionReponse',
    'supprimer.optionReponse',
    'creer.versionModeleQuestionnaire', //
    'modifier.versionModeleQuestionnaire',
    'enregistrer.versionModeleQuestionnaire',
    'lister.versionModeleQuestionnaire',
    'retourListe.versionModeleQuestionnaire',
    'consulter.versionModeleQuestionnaire',
    'ajouter.versionModeleQuestionnaire',
    'chercher.versionModeleQuestionnaire',
    'filtrer.versionModeleQuestionnaire',
    'supprimer.versionModeleQuestionnaire',
    'creer.sessionInterview', //
    'modifier.sessionInterview',
    'enregistrer.sessionInterview',
    'lister.sessionInterview',
    'retourListe.sessionInterview',
    'consulter.sessionInterview',
    'ajouter.sessionInterview',
    'chercher.sessionInterview',
    'filtrer.sessionInterview',
    'supprimer.sessionInterview',
    'creer.etatVersionModeleQuestionnaire', //
    'modifier.etatVersionModeleQuestionnaire',
    'enregistrer.etatVersionModeleQuestionnaire',
    'lister.etatVersionModeleQuestionnaire',
    'retourListe.etatVersionModeleQuestionnaire',
    'consulter.etatVersionModeleQuestionnaire',
    'ajouter.etatVersionModeleQuestionnaire',
    'chercher.etatVersionModeleQuestionnaire',
    'filtrer.etatVersionModeleQuestionnaire',
    'supprimer.etatVersionModeleQuestionnaire',
    'creer.transition', //
    'modifier.transition',
    'enregistrer.transition',
    'lister.transition',
    'retourListe.transition',
    'consulter.transition',
    'ajouter.transition',
    'chercher.transition',
    'filtrer.transition',
    'supprimer.transition',
    'creer.option', //
    'modifier.option',
    'enregistrer.option',
    'lister.option',
    'retourListe.option',
    'consulter.option',
    'ajouter.option',
    'chercher.option',
    'filtrer.option',
    'supprimer.option',
    'creer.contrat', //
    'modifier.contrat',
    'enregistrer.contrat',
    'lister.contrat',
    'retourListe.contrat',
    'consulter.contrat',
    'ajouter.contrat',
    'chercher.contrat',
    'filtrer.contrat',
    'supprimer.contrat',
    'creer.identificationSinistre', //
    'modifier.identificationSinistre',
    'enregistrer.identificationSinistre',
    'lister.identificationSinistre',
    'retourListe.identificationSinistre',
    'consulter.identificationSinistre',
    'ajouter.identificationSinistre',
    'chercher.identificationSinistre',
    'filtrer.identificationSinistre',
    'supprimer.identificationSinistre',
    'creer.motif', //
    'modifier.motif',
    'enregistrer.motif',
    'lister.motif',
    'retourListe.motif',
    'consulter.motif',
    'ajouter.motif',
    'chercher.motif',
    'filtrer.motif',
    'supprimer.motif',
    'creer.tache', //
    'modifier.tache',
    'enregistrer.tache',
    'lister.tache',
    'retourListe.tache',
    'consulter.tache',
    'ajouter.tache',
    'chercher.tache',
    'filtrer.tache',
    'supprimer.tache',
    'creer.modeleQuestionnaire', //
    'modifier.modeleQuestionnaire',
    'enregistrer.modeleQuestionnaire',
    'lister.modeleQuestionnaire',
    'retourListe.modeleQuestionnaire',
    'consulter.modeleQuestionnaire',
    'ajouter.modeleQuestionnaire',
    'chercher.modeleQuestionnaire',
    'filtrer.modeleQuestionnaire',
    'supprimer.modeleQuestionnaire',
    'retour',
];
const ROLE_ADMIN = [];
const rightMap = {
    ALL,
    ROLE_ADMIN,
};

export default function useHasRight(action): boolean {
    const user = useAppSelector((state) => state.storeAuth.user);
    return rightMap['ALL'].includes(action) || rightMap[user.role].includes(action);
}